import axios from 'axios';
import { demoParts, demoCars } from './demoData';
const api = axios.create({ baseURL: '/api' });
const filterParts = (params={}) => demoParts.filter(p => (!params.q || (p.name+p.brand+p.id+p.oem+p.fitment).toLowerCase().includes(params.q.toLowerCase())) && (!params.brand || params.brand==='All' || p.brand===params.brand) && (!params.category || params.category==='All' || p.category===params.category));
const filterCars = (params={}) => demoCars.filter(c => (!params.q || c.title.toLowerCase().includes(params.q.toLowerCase())) && (!params.condition || params.condition==='All' || c.condition===params.condition));
export const getParts = (params={}) => api.get('/parts',{params}).then(r=>r.data).catch(()=>filterParts(params));
export const getCars = (params={}) => api.get('/cars',{params}).then(r=>r.data).catch(()=>filterCars(params));
export const vinDecode = (vin) => api.get(`/vin/${vin}`).then(r=>r.data);
const local = (key, fallback=[]) => JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));
const save = (key, value) => localStorage.setItem(key, JSON.stringify(value));
export const importQuote = (body) => api.post('/import-quote', body).then(r=>r.data).catch(()=>{ const cif=Number(body.cif||20000), duty=cif*.2+(Number(body.engineCC)>2000?cif*.1:0)+(Number(body.age)>5?500:0), gct=(cif+duty)*.15; const q={...body,cif,duty:Math.round(duty),gct:Math.round(gct),broker:280,handling:350,total:Math.round(cif+duty+gct+630),eta:'25-35 days via Kingston Port',id:'Q-DEMO'}; save('alrobe-quotes',[q,...local('alrobe-quotes')]); return q; });
export const createOrder = (body) => api.post('/orders', body).then(r=>r.data).catch(()=>{ const o={...body,id:'ALR-DEMO',status:'Received - Kingston Free Zone',payment_method:body.payment_method||'pickup',payment_status:'pending'}; save('alrobe-orders',[o,...local('alrobe-orders')]); return o; });
export const track = (id) => api.get(`/track/${id}`).then(r=>r.data).catch(()=>({id:id.toUpperCase(),status:'Kingston Free Zone Pick/Pack',payment_status:'pending',progress:33,stages:['Order Received','Kingston Free Zone Pick/Pack','Customs Cleared','In Transit / On Vessel','Out for Delivery','Delivered'],updated:new Date().toISOString(),location:'Port of Kingston, Jamaica'}));
export const sendContact = (body) => api.post('/contact', body).then(r=>r.data).catch(()=>{ save('alrobe-contacts',[{...body,created:new Date().toISOString()},...local('alrobe-contacts')]); return {ok:true,message:'Received! Our Kingston team will call you Mon-Fri 10am-4pm.'}; });
export const getOrders = () => api.get('/orders').then(r=>r.data).catch(()=>local('alrobe-orders'));
export const getQuotes = () => api.get('/quotes').then(r=>r.data).catch(()=>local('alrobe-quotes'));
export const getMethods = () => api.get('/payments/methods').then(r=>r.data).catch(()=>({methods:[{id:'pickup',label:'Cash on Pickup'},{id:'bank',label:'Bank Transfer'},{id:'lynk',label:'Lynk / WiPay'},{id:'card',label:'Card (Stripe)'},{id:'whatsapp',label:'WhatsApp Order'}]}));
export const createIntent = (body) => api.post('/payments/create-intent', body).then(r=>r.data).catch(()=>({mock:true,clientSecret:'demo_'+Date.now(),message:'Demo card intent created.'}));
export const confirmPayment = (body) => api.post('/payments/confirm', body).then(r=>r.data).catch(()=>({ok:true,...body}));
export const getPayments = () => api.get('/payments').then(r=>r.data).catch(()=>[]);
export const getContacts = () => api.get('/contacts').then(r=>r.data).catch(()=>local('alrobe-contacts'));
export const patchOrder = (id, body) => api.patch(`/orders/${id}`, body).then(r=>r.data).catch(()=>{ const orders=local('alrobe-orders').map(o=>o.id===id?{...o,...body}:o); save('alrobe-orders',orders); return orders.find(o=>o.id===id); });
export default api;
