import axios from 'axios';
import { demoParts, demoCars } from './demoData';
const api = axios.create({ baseURL: '/api' });
const filterParts = (params={}) => demoParts.filter(p => (!params.q || (p.name+p.brand+p.id+p.oem+p.fitment).toLowerCase().includes(params.q.toLowerCase())) && (!params.brand || params.brand==='All' || p.brand===params.brand) && (!params.category || params.category==='All' || p.category===params.category));
const filterCars = (params={}) => demoCars.filter(c => (!params.q || c.title.toLowerCase().includes(params.q.toLowerCase())) && (!params.condition || params.condition==='All' || c.condition===params.condition));
const dataOrFail = (r, valid) => valid(r.data) ? r.data : Promise.reject(new Error('Unexpected API response'));
export const getParts = (params={}) => api.get('/parts',{params}).then(r=>dataOrFail(r,Array.isArray)).catch(()=>filterParts(params));
export const getCars = (params={}) => api.get('/cars',{params}).then(r=>dataOrFail(r,Array.isArray)).catch(()=>filterCars(params));
export const vinDecode = (vin) => api.get(`/vin/${vin}`).then(r=>dataOrFail(r,d=>d && typeof d==='object' && d.vin)).catch(()=>({vin:vin.toUpperCase(),make:vin.startsWith('J')?'Toyota (Japan)':'Honda',model:'Corolla / Vezel class',year:2021,engine:'1.8L Hybrid / 1.5L Petrol',recommended:['BOS-1150','FEB-7701','BOS-2204']}));
const local = (key, fallback=[]) => JSON.parse(localStorage.getItem(key)||JSON.stringify(fallback));
const save = (key, value) => localStorage.setItem(key, JSON.stringify(value));
const quoteFallback = (body) => { const cif=Number(body.cif||20000), duty=cif*.2+(Number(body.engineCC)>2000?cif*.1:0)+(Number(body.age)>5?500:0), gct=(cif+duty)*.15; const q={...body,cif,duty:Math.round(duty),gct:Math.round(gct),broker:280,handling:350,total:Math.round(cif+duty+gct+630),eta:'25-35 days via Kingston Port',id:'Q-DEMO'}; save('alrobe-quotes',[q,...local('alrobe-quotes')]); return q; };
export const importQuote = (body) => api.post('/import-quote', body).then(r=>dataOrFail(r,d=>d && typeof d==='object' && d.total)).catch(()=>quoteFallback(body));
export const createOrder = (body) => api.post('/orders', body).then(r=>dataOrFail(r,d=>d && typeof d==='object' && d.id)).catch(()=>{ const o={...body,id:'ALR-DEMO',status:'Received - Kingston Free Zone',payment_method:body.payment_method||'pickup',payment_status:'pending'}; save('alrobe-orders',[o,...local('alrobe-orders')]); return o; });
const trackFallback = (id) => ({id:id.toUpperCase(),status:'Kingston Free Zone Pick/Pack',payment_status:'pending',progress:33,stages:['Order Received','Kingston Free Zone Pick/Pack','Customs Cleared','In Transit / On Vessel','Out for Delivery','Delivered'],updated:new Date().toISOString(),location:'Port of Kingston, Jamaica'});
export const track = (id) => api.get(`/track/${id}`).then(r=>dataOrFail(r,d=>d && typeof d==='object' && d.stages)).catch(()=>trackFallback(id));
export const sendContact = (body) => api.post('/contact', body).then(r=>dataOrFail(r,d=>d && d.ok)).catch(()=>{ save('alrobe-contacts',[{...body,created:new Date().toISOString()},...local('alrobe-contacts')]); return {ok:true,message:'Received! Our Kingston team will call you Mon-Fri 10am-4pm.'}; });
export const getOrders = () => api.get('/orders').then(r=>dataOrFail(r,Array.isArray)).catch(()=>local('alrobe-orders'));
export const getQuotes = () => api.get('/quotes').then(r=>dataOrFail(r,Array.isArray)).catch(()=>local('alrobe-quotes'));
const demoMethods = {methods:[{id:'pickup',label:'Cash on Pickup'},{id:'bank',label:'Bank Transfer'},{id:'lynk',label:'Lynk / WiPay'},{id:'card',label:'Card (Stripe)'},{id:'whatsapp',label:'WhatsApp Order'}]};
export const getMethods = () => api.get('/payments/methods').then(r=>dataOrFail(r,d=>d && Array.isArray(d.methods))).catch(()=>demoMethods);
export const createIntent = (body) => api.post('/payments/create-intent', body).then(r=>dataOrFail(r,d=>d && typeof d==='object' && (d.clientSecret||d.id))).catch(()=>({mock:true,clientSecret:'demo_'+Date.now(),message:'Demo card intent created.'}));
export const confirmPayment = (body) => api.post('/payments/confirm', body).then(r=>dataOrFail(r,d=>d && d.ok)).catch(()=>({ok:true,...body}));
export const getPayments = () => api.get('/payments').then(r=>dataOrFail(r,Array.isArray)).catch(()=>[]);
export const getContacts = () => api.get('/contacts').then(r=>dataOrFail(r,Array.isArray)).catch(()=>local('alrobe-contacts'));
export const patchOrder = (id, body) => api.patch(`/orders/${id}`, body).then(r=>dataOrFail(r,d=>d && d.id)).catch(()=>{ const orders=local('alrobe-orders').map(o=>o.id===id?{...o,...body}:o); save('alrobe-orders',orders); return orders.find(o=>o.id===id); });
export default api;
